[package]
name = "rust_fincalc"
authors = ["Dane Skalski (daneski13)"]
edition = "2021"
description = "Various finance and accounting calculations/formulas implemented Rust"
readme = "./README.md"
repository = "https://github.com/daneski13/rust-fincalc"
documentation = "https://daneski13.github.io/rust-fincalc/rust_fincalc/index.html"
license = "MIT"
keywords = ["finance", "math", "financial", "money", "excel", "economics"]
categories = ["finance", "mathematics"]
rust-version = "1.78.0"


[dependencies]
rust_decimal = { version = "1.35.0", default-features = false, features = [
	"maths",
	"std",
] }
rust_decimal_macros = "1.34.2"
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
serde = ["dep:serde", "rust_decimal/serde"]

[dev-dependencies]
criterion = "0.5.1"
serde_json = "1.0.117"

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "./src/docs-header.html"]

[[bench]]
name = "my_benchmark"
harness = false
